### ISSUE TITLE
Unnecessary __init__.py in dataset/

### ISSUE THREAD

**Issue by bornabesic** [alpemek/aerial-segmentation#4]
Hi,

`dataset/` directory is only used to store downloaded data and it's not a package. However, it contains [`__init__.py`](https://github.com/alpemek/aerial-segmentation/blob/master/dataset/__init__.py) file. This should be removed in the next commit. If unfamiliar, read more on Python packages [here](https://docs.python.org/3/tutorial/modules.html#packages).

Best regards

**Comment by alpemek** [comment]
Hi,

thank you for noticing it. It was first designed as a module, then changed to a data storage folder. It was indeed a mistake to keep the `__init__.py` file. Fixed after https://github.com/alpemek/aerial-segmentation/commit/73af9533dfd4add9d328e20bd2ee0cff81cc52c3.
